---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_solo
  legacy_mode: true
  chef_license: accept-no-persist
  environments_path: environments
  client_rb:
    add_formatter: min
  solo_rb:
    file_atomic_update: false

platforms:
  - name: centos-7-chef-13
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum update -y
        - yum install epel-release -y
        - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
        - yum install rsyslog -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh

verifier:
  name: inspec

suites:
  - name: jumpcloud
    attributes:
      jumpcloud:
        # No idea whos connect-key this is, its linked here.. Going to use it for travis tests though
        # https://support.jumpcloud.com/customer/portal/articles/2443855--linux-installing-the-jumpcloud-agent-using-chef
        connect_key: 'ec78281415d4e9992aaacb906c2ae708c6c92b63'
    run_list:
        - jumpcloud
    verifier:
      inspec_tests:
        - tests/jumpcloud.rb
  - name: jumpcloud-for-image
    attributes:
      jumpcloud:
        connect_key: 'ec78281415d4e9992aaacb906c2ae708c6c92b63'
        prepare_for_image: true
    run_list:
        - jumpcloud
    verifier:
      inspec_tests:
        - tests/jumpcloud.rb
  - name: jumpcloud-with-api
    attributes:
      jumpcloud:
        connect_key: 'ec78281415d4e9992aaacb906c2ae708c6c92b63'
        api_key: 'test-1234'
    run_list:
        - jumpcloud
    verifier:
      inspec_tests:
        - tests/jumpcloud.rb
        - tests/jumpcloud-api.rb
