---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - yum update yum ca-certificates -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-7-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - yum update yum ca-certificates -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: centos-69-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum update yum ca-certificates -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: centos-69
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum update yum ca-certificates -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

suites:
  - name: jumpcloud
    attributes:
      jumpcloud:
        # No idea whos connect-key this is, its linked here.. Going to use it for travis tests though
        # https://support.jumpcloud.com/customer/portal/articles/2443855--linux-installing-the-jumpcloud-agent-using-chef
        connect_key: 'ec78281415d4e9992aaacb906c2ae708c6c92b63'
    run_list:
        - jumpcloud
    verifier:
      inspec_tests:
        - tests/jumpcloud.rb
  - name: jumpcloud-for-image
    attributes:
      jumpcloud:
        connect_key: 'ec78281415d4e9992aaacb906c2ae708c6c92b63'
        prepare_for_image: true
    run_list:
        - jumpcloud
    verifier:
      inspec_tests:
        - tests/jumpcloud.rb
